### ISSUE TITLE
Add readme. Include setup 

### ISSUE THREAD

**Issue by m-rest** [RT-WDF/rt-wdf_renderer#4]
incl. 
## Setup
git submodule init
git submodule update

and Submodule update procedure as in http://stackoverflow.com/questions/7813030/how-can-i-have-linked-dependencies-in-a-git-repo

**Comment by chohner** [comment]
mention `xcodebuild -project wdfRenderer.xcodeproj -alltargets -configuration Release` for people that dont want to open xcode or only have command line tools installed.

**Comment by chohner** [comment]
also, add description
